[application]

[web.app]

# HTML title tag content
title = "Stay Ahead"

# For Github Pages, I need to add this base path so
# that the website is rendered at the correct url
#
base_path = "StayAhead"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

[bundle]
icon = ["assets/icons/favicon_highres.ico"]
identifier = "com.paleggworks"
publisher = "Palegg Works"
